name: CloudFormation Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy CloudFormation Stack
        uses: mgenteluci/cloudformation-deploy-action@v1.4.1
        env:
          TEMPLATE: 'deploy.yml'
          AWS_STACK_NAME: 'EC2Stack'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEPLOY_BUCKET: ${{secrets.AWS_DEPLOY_BUCKET}}
